#!/usr/bin/env python3
# Copyright (c) 2014 Open Grid Computing, Inc. All rights reserved.
# Copyright (c) 2019 NTESS Corporation. All rights reserved.
# Under the terms of Contract DE-AC04-94AL85000, there is a non-exclusive
# license for use of this work by or on behalf of the U.S. Government.
# Export of this program may require a license from the United States
# Government.
#
# This software is available to you under a choice of one of two
# licenses.  You may choose to be licensed under the terms of the GNU
# General Public License (GPL) Version 2, available from the file
# COPYING in the main directory of this source tree, or the BSD-type
# license below:
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#      Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#      Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#
#      Neither the name of NTESS Corporation, Open Grid Computing nor
#      the names of any contributors may be used to endorse or promote
#      products derived from this software without specific prior
#      written permission.
#
#      Modified source versions must be plainly marked as such, and
#      must not be misrepresented as being the original software.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
from builtins import str
import sys
import argparse
from sosdb import Sos

def fmt_size(size):
    if size < 1000.0:
        return f"{size:8.1f}B"
    size /= 1000.0
    if size < 1000.0:
        return f"{size:8.1f}KB"
    size /= 1000.0
    if size < 1000.0:
        return f"{size:8.1f}MB"
    size /= 1000.0
    if size < 1000.0:
        return f"{size:8.1f}GB"
    size /= 1000.0
    if size < 1000.0:
        return f"{size:8.1f}TB"
    size /= 1000.0
    return "{size:8.1f}PB"

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create a SOS DB")
    actions = parser.add_mutually_exclusive_group(required=True)
    actions.add_argument("--create", action="store_true",
                        help="Create a new SOS database. " \
                        "The --path parameter specifies the path to the new " \
                        "database.")
    actions.add_argument("--query", action="store_true",
                        help="Query a container's partition information")
    actions.add_argument("--transaction",
                        help="Start/End a container transaction")
    actions.add_argument("--locks", action="store_true",
                        help="Print active container locks")
    actions.add_argument("--stats", action="store_true",
                        help="Print active partition configuration")
    parser.add_argument("--timeout", type=int,
                        help="Transaction timeout in seconds")
    parser.add_argument("--path", required=True,
                        help="The path to the database.")
    parser.add_argument("--mode", metavar="PERM", default="0o660",
                        help="The permissions to assign to SOS database files. "
                        "Specified as an octal number, e.g. 0o666")
    parser.add_argument("--backend", metavar="NAME", default="MMOS",
                        help="Specifies the back-end storage strategy. " \
                        "Supported values are 'mmos' and 'lsos'. The default is 'mmos'")

    args = parser.parse_args()

    cont = Sos.Container()

    if args.create:
        try:
            # Create the database
            perm = Sos.PERM_CREAT
            if args.backend.lower() == "lsos":
                perm |= Sos.BE_LSOS
            if args.mode:
                cont.open(args.path, perm, o_mode=int(args.mode, base=0))
            else:
                cont.open(args.path, perm)
        except Exception as ex:
            print(f"The container {args.path} could not be created.")
            print(str(ex))
            sys.exit(1)

    if args.query:
        import datetime as dt
        try:
            cont.open(args.path)
        except Exception as e:
            print(f"The container {args.path} could not be opened.")
            print(str(e))
            sys.exit(1)

        pi = cont.part_iter()
        print(f"{'Name':18} {'State':10} {'Accessed':18} {'Modified':18} {'Size':10} {'Path'}")
        print(f"{'-'*18} {'-'*10} {'-'*18} {'-'*18} {'-'*10} {'-'*20}")
        for p in pi:
            stat = p.stat()
            accessed = dt.datetime.fromtimestamp(stat.accessed)
            modified = dt.datetime.fromtimestamp(stat.modified)
            print(f"{p.name():18} {str(p.state()):10} "
                  f"{accessed.strftime('%m/%d/%y %H:%M:%S'):18} "
                  f"{modified.strftime('%m/%d/%y %H:%M:%S'):18} "
                  f"{fmt_size(stat.size):10} {p.path()}")

    if args.stats:
        Sos.cont_stats(args.path)

    if args.transaction:
        try:
            cont.open(args.path)
        except Exception as ex:
            print(f"The container {args.path} could not be opened.")
            sys.exit(1)
        if args.transaction.lower() == "begin":
            rc = cont.begin(timeout=args.timeout)
            if rc != 0:
                print(f"The transaction is held by process {rc}")
        elif args.transaction.lower() == "end":
            cont.end()
        else:
            print("The transaction argument must be 'begin' or 'end'")
            sys.exit(1)

    if args.locks:
        Sos.lock_info(args.path)
