#!/usr/bin/env python3
# Copyright (c) 2023 Open Grid Computing, Inc. All rights reserved.
# Copyright (c) 2019 NTESS Corporation. All rights reserved.
# Under the terms of Contract DE-AC04-94AL85000, there is a non-exclusive
# license for use of this work by or on behalf of the U.S. Government.
# Export of this program may require a license from the United States
# Government.
#
# This software is available to you under a choice of one of two
# licenses.  You may choose to be licensed under the terms of the GNU
# General Public License (GPL) Version 2, available from the file
# COPYING in the main directory of this source tree, or the BSD-type
# license below:
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#      Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#      Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#
#      Neither the name of NTESS Corporation, Open Grid Computing nor
#      the names of any contributors may be used to endorse or promote
#      products derived from this software without specific prior
#      written permission.
#
#      Modified source versions must be plainly marked as such, and
#      must not be misrepresented as being the original software.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
from builtins import str
import shutil
import sys
import os
import errno
import argparse
import pwd
import grp
import uuid
from sosdb import Sos

def fmt_size(size):
    if size < 1024.0:
        return "{0:8}B".format(int(size))
    size /= 1024.0
    if size < 1024.0:
        return "{0:8.1f}K".format(size)
    size /= 1024.0
    if size < 1024.0:
        return "{0:8.1f}M".format(size)
    size /= 1024.0
    if size < 1024.0:
        return "{0:8.1f}G".format(size)
    size /= 1024.0
    if size < 1024.0:
        return "{0:8.1f}T".format(size)
    size /= 1024.0
    return "{0:8.1f}P".format(size)

class Permission:
    translate = {
        0o1   : [ '-', 'x' ],
        0o2   : [ '-', 'w' ],
        0o4   : [ '-', 'r' ],
        0o10  : [ '-', 'x' ],
        0o20  : [ '-', 'w' ],
        0o40  : [ '-', 'r' ],
        0o100 : [ '-', 'x' ],
        0o200 : [ '-', 'w' ],
        0o400 : [ '-', 'r' ]
    }
    def __init__(self, mask):
        self.mask = mask

    def __str__(self):
        s = ''
        for m in self.translate:
            if 0 != (m & self.mask):
                s = self.translate[m][1] + s
            else:
                s = self.translate[m][0] + s
        return s

def print_table(p, hdr=True, ftr=False, verbose=False):
    if hdr:
        if int(p.state()) != Sos.PART_STATE_DETACHED:
            print("{0:18} {1:10} ".format("Name", "State"), end='')
        print("{0:24} {1:24} {2:12} {3:10} {4:36}".
                format("User", "Group", "Permissions", "Size", "Description"), end='')
        if verbose:
            print(" {0:36}".format("UUID"), end='')
        if int(p.state()) != Sos.PART_STATE_DETACHED:
            print(" {0:20}".format("Path"), end='')
        print("")

    if hdr or ftr:
        if int(p.state()) != Sos.PART_STATE_DETACHED:
            print("{0} {1} ".format('-'.ljust(18,'-'), '-'.ljust(10,'-')), end='')
        print("{0} {1} {2} {3} {4}".
                format('-'.ljust(24, '-'), '-'.ljust(24, '-'), '-'.ljust(12, '-'),
                       '-'.ljust(10,'-'), '-'.ljust(36,'-')), end='')
        if verbose:
            print(" {0}".format('-'.ljust(36, '-')), end='')
        if int(p.state()) != Sos.PART_STATE_DETACHED:
            print(" {0}".format('-'.ljust(20, '-')), end='')
        print("")

    if ftr:
        return

    stat = p.stat()
    try:
        uid = pwd.getpwuid(int(p.uid()))
        uid = uid.pw_name
    except:
        uid = p.uid()
    try:
        gid = grp.getgrgid(int(p.gid()))
        gid = gid.gr_name
    except:
        gid = p.gid()
    perm = Permission(p.perm())
    accessed = dt.datetime.fromtimestamp(stat.accessed)
    modified = dt.datetime.fromtimestamp(stat.modified)

    if int(p.state()) != Sos.PART_STATE_DETACHED:
        print("{0:18} {1:10} ".format(p.name(), str(p.state())), end='')
    print("{0:24} {1:24} {2:12} {3:10} {4:36}". \
            format(uid, gid, str(perm), fmt_size(stat.size), p.desc()), end='')
    if verbose:
        print(" {0:36}".format(str(p.uuid())), end='')
    if int(p.state()) != Sos.PART_STATE_DETACHED:
        print(" {0}".format(p.path()), end='')
    print("")

def print_json(p, hdr=True, ftr=False):
    if ftr:
        print("]")
        return
    if hdr:
        print("[")
    else:
        print(",")
    stat = p.stat()
    uid = p.uid()
    gid = p.gid()
    perm = Permission(p.perm())
    accessed = dt.datetime.fromtimestamp(stat.accessed)
    accessed = accessed.strftime("%m/%d/%y %H:%M:%S")
    modified = dt.datetime.fromtimestamp(stat.modified)
    modified = modified.strftime("%m/%d/%y %H:%M:%S")
    print(f'{{ "name": "{p.name()}", "state" : "{str(p.state())}", '
          f'"uid" : {uid}, "gid" : {gid}, "perm" : "{str(perm)}", '
          f'"access" : "{accessed}", "modified" : "{modified}", '
          f'"size" : {stat.size}, "path" : "{p.path()}", '
          f'"description" : "{p.desc()}", ',
          f'"UUID" : "{str(p.uuid())}"}}', end='')

def print_partition(p, hdr=True, ftr=False, verbose=False, fmt='table'):
    if fmt == 'table':
        print_table(p, hdr, ftr, verbose)
    else:
        print_json(p, hdr, ftr)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Manage SOSDB partitions.")
    actions = parser.add_mutually_exclusive_group(required=True)
    actions.add_argument("--query", action="store_true",
                        help="Query a partition.")
    actions.add_argument("--create", action="store_true",
                         help="Create a new partition. ")
    actions.add_argument("--set", action="store_true",
                         help="Set user-id, group-id, and permission bits"
                            "for accessing a partition's contents")
    actions.add_argument("--attach", action="store_true",
                         help="Attach a partition to a container.")
    actions.add_argument("--state", metavar="STATE-NAME",
                         choices=[ 'primary', 'PRIMARY', 'active', 'ACTIVE',
                                   'offline', 'OFFLINE' ],
                         help="Set the state of a partition.")
    actions.add_argument("--detach", action="store_true",
                         help="Detach a partition from a container.")
    actions.add_argument("--remap-schema", action="store_true",
                         help="Replace the schema UUID in a partition. "
                         "Used when importing a partition that was populated "
                         "using a different schema dictionary.")
    actions.add_argument("--show-schema", action="store_true",
                         help="Show the set of schema UUID that are "
                         "used by objects in the partition.")
    actions.add_argument("--reindex", action="store_true",
                         help="Reindex all objects in the specified partition")
    actions.add_argument("--verify", action="store_true",
                         help="Verify the signature in all ODS in the partition")

    parser.add_argument("--path", metavar="DB-PATH", required=False,
                        help="Specifies the path to the partition.")
    parser.add_argument("--cont", default=None, metavar="PATH",
                        help="The path to the container used with the "
                        "--attach, --detach, and --query actions.")
    parser.add_argument("--name", metavar="PART-NAME", default=None,
                        help="Specifies the parition name.")
    parser.add_argument("--mode", metavar="MODE", default=None,
                        help="The file access mode if creating a partition")
    parser.add_argument("--user", metavar="USER", default=None,
                        help="The user name or user-id that owns the container")
    parser.add_argument("--group", metavar="GROUP", default=None,
                        help="The group name or group-id that owns the container")
    parser.add_argument("--backend", metavar="BACKEND", default='MMOS',
                        help="The desired storage backend, one of: "
                        "'LSOS' (Log Structured Object Store), or "
                        "'MMOS' (Memory Mapped Object Store). "
                        " The default is 'MMOS'.")
    parser.add_argument("--desc", default=None,
                        help="A description for the partition.")
    parser.add_argument("--fmt", default='table',
                        help="The desired query output format: 'table', or 'json'.")
    parser.add_argument("--cur-dir", metavar="PATH",
                        help="Path to the template directory definining the "
                        "schema UUID currently in use in the partition.")
    parser.add_argument("--new-dir", metavar="PATH",
                        help="Path to the template directory definining the "
                        "schema UUID that will replace the current UUID.")
    parser.add_argument("--verbose", action="store_true",
                        help="Use with --query to show the partition UUID")
    parser.add_argument("--reindex-status-count", type=int, metavar="OBJ-COUNT", default=10000,
                        help="The number of objects to update before printing a status message")
    args = parser.parse_args()

    #
    # Query the partitions
    #
    if args.query:
        import datetime as dt
        if args.cont:
            # Open the database
            cont = Sos.Container()
            try:
                cont.open(args.cont)
            except Exception as ex:
                print(f" The container '{args.cont}' could not be opened.")
                sys.exit(1)
        else:
            cont = None
        if cont:
            pi = cont.part_iter()
            hdr = True
            p = None
            for p in pi:
                print_partition(p, hdr, fmt=args.fmt, verbose=args.verbose)
                hdr = False
            if p:
                print_partition(p, hdr=False, ftr=True, fmt=args.fmt,
                                verbose=args.verbose)
            else:
                print("There are no partitions user "
                      f"{os.geteuid()} group {os.getegid()} is authorized to view")
            sys.exit(0)
        if not args.path:
            print(f"One of --cont or --path must be specified.")
            sys.exit(1)
        try:
            p = Sos.Partition()
            p.open(args.path)
        except Exception as e:
            print(f"The partition '{args.path}' could not be opened.")
            sys.exit(1)
        print_partition(p, fmt=args.fmt)
        sys.exit(0)

    def get_uid(args, default):
        if args.user:
            if type(args.user) == str:
                if args.user.isdigit():
                    uid = int(args.user)
                else:
                    pwe = pwd.getpwnam(args.user)
                    uid = pwe.pw_uid
            else:
                uid = int(args.user)
        else:
            uid = default
        return uid

    def get_gid(args, default):
        if args.group:
            if type(args.group) == str:
                if args.group.isdigit():
                    gid = int(args.group)
                else:
                    gr = grp.getgrnam(args.group)
                    gid = gr.gr_gid
            else:
                gid = int(args.group)
        else:
            gid = default
        return gid

    #
    # Create a partition
    #
    if args.create:
        try:
            if args.backend.upper() == 'LSOS':
                backend = Sos.BE_LSOS
            elif args.backend.upper() == 'MMOS':
                backend = Sos.BE_MMOS
            else:
                print("The storage backend must be 'LSOS' or 'MMOS'.")
                sys.exit(1)
            if args.desc:
                description = args.desc
            else:
                description = None
            if args.user and not args.group:
                print("The user name (--user) must be specified.")
                sys.exit(1)
            part = Sos.Partition()
            if args.mode:
                mode = int(args.mode, base=0)
            else:
                mode = 0o660
            try:
                part.open(args.path,
                    o_perm = Sos.PERM_RW | Sos.PERM_CREAT,
                    o_mode = mode,
                    desc = description, backend = backend)
            except Exception as e:
                print(f"The partition '{args.path}' could not be created.")
                sys.exit(1)

            uid = get_uid(args, os.getuid())
            gid = get_gid(args, os.getgid())
            if args.user or args.group:
                part.chown(uid, gid)
            part.chmod(mode)
        except Exception as ex:
            print("An error was encountered creating the partition.\n{0}".format(ex))
            sys.exit(1)
        sys.exit(0)

    #
    # Change a partition's ownership and access rights
    #
    if args.set:
        part = Sos.Partition()
        try:
            part.open(args.path)
        except Exception as e:
            print(f"The partition '{args.path}' could not be opened.")
            sys.exit(1)
        if args.desc:
            part.desc_set(args.desc)
        uid = get_uid(args, -1)
        gid = get_gid(args, -1)
        if args.user or args.group:
            part.chown(uid, gid)
        if args.mode:
            part.chmod(int(args.mode, base=0))

    #
    # Check the --cont, --path and --name options
    #
    if args.attach or args.detach or args.state:
        if (args.state or args.attach or args.detach) and not args.name:
            print("The partition name (--name NAME) must be specified")
            sys.exit(1)
        if args.attach and not args.path:
            print("The partition path (--path PATH) must be specified with --attach")
            sys.exit(1)
        if not args.cont:
            print("The container option (--cont PATH) must be specified.")
            sys.exit(1)
        # Open the database
        cont = Sos.Container()
        try:
            cont.open(args.cont)
        except Exception as ex:
            print(f"The container '{args.cont}' could not be opened.")
            sys.exit(1)

    #
    # Change the state of a partition
    #
    if args.state:
        part = cont.part_by_name(args.name)
        if not part:
            print(f"The part name '{args.name}' was not found.")
            sys.exit(1)
        try:
            part.state_set(args.state)
        except Exception as ex:
            print(f"The state '{args.state}' could not be set.")
            sys.exit(1)
        sys.exit(0)

    #
    # Attach a partition to a container
    #
    if args.attach:
        part = Sos.Partition()
        try:
            part.open(args.path)
        except Exception as e:
            print(f"The partition '{args.path}' could not be opened")
            sys.exit(1)
        try:
            part.attach(cont, args.name)
        except Exception as e:
            if part.errno() == errno.EEXIST:
                print(f"A partition with this name or path already exists in the container.")
            elif part.errno() == errno.EPERM:
                print(f"You do not have sufficient permission to attach this container/partition.")
            else:
                print(f"Error '{str(e)}' attaching partition '{args.name}'.")
            sys.exit(1)

    #
    # Detach a partition from a container
    #
    if args.detach:
        try:
            cont.part_detach(args.name)
        except:
            print(f"The partition '{args.name}' could not be detached")
            sys.exit(1)

    #
    # Remap a partition's schema UUID
    #
    if args.remap_schema:
        part = Sos.Partition()
        try:
            part.open(args.path)
        except:
            print(f"The partition '{args.path}' could not be opened")
            sys.exit(1)
        count, err = part.remap_schema_uuid(args.new_dir, args.cur_dir)
        print(f"{count} objects were updated with new schema UUID.")
        if err != 0:
            if err == errno.ENOENT:
                print(f"The {args.new_dir} or {args.cur_dir} files could not " \
                      "be opened.")
            elif err == errno.EINVAL:
                print(f"The {args.new_dir} or {args.cur_dir} files are not " \
                      "valid JSON.")
            elif err != 0:
                print(f"Error {err} was returned remapping the partition's UUID")
        sys.exit(1)
    #
    # Show a partition's schema UUID
    #
    if args.show_schema:
        if args.path is None:
            print("The --path PATH argument is required for --show-schma")
            sys.exit(1)
        part = Sos.Partition()
        try:
            part.open(args.path)
        except:
            print(f"The partition '{args.path}' could not be opened")
            sys.exit(1)
        uuid_list = part.query_schema_uuid()
        print("Schema UUID                          Use Count")
        print("------------------------------------ ------------")
        obj_count = 0
        for entry in uuid_list:
            u = uuid.UUID(bytes=entry[0][0:16])
            obj_count += entry[1]
            print(f"{str(u)} {entry[1]:>12}")
        print("------------------------------------ ------------")
        print(f"{'':36} {obj_count:>12}")
        sys.exit(0)
    #
    # Rebuild all the indices in a partition
    #
    if args.reindex:
        if not args.cont:
            print("The container option (--cont PATH) must be specified.")
            sys.exit(1)
        if not args.name:
            print("The partition name (--name PART-NAME) must be specified.")
            sys.exit(1)
        cont = Sos.Container()
        try:
            cont.open(args.cont)
        except Exception as ex:
            print(f" The container '{args.cont}' could not be opened.")
            sys.exit(1)
        part = cont.part_by_name(args.name)
        if not part:
            print(f"The partition '{args.name}' was not found.")
            sys.exit(1)
        try:
            part.reindex(args.reindex_status_count)
        except Exception as e:
            print(e)
            sys.exit(1)
    #
    # Verify the partition ODS
    #
    if args.verify:
        if not args.path:
            print("The partition path (--path PATH) must be specified.")
            sys.exit(1)
        part = Sos.Partition()
        part.verify(args.path, sys.stdout)

    sys.exit(0)
