#!/usr/bin/env python
# Copyright (c) 2014 Open Grid Computing, Inc. All rights reserved.
# Copyright (c) 2019 NTESS Corporation. All rights reserved.
# Under the terms of Contract DE-AC04-94AL85000, there is a non-exclusive
# license for use of this work by or on behalf of the U.S. Government.
# Export of this program may require a license from the United States
# Government.
#
# This software is available to you under a choice of one of two
# licenses.  You may choose to be licensed under the terms of the GNU
# General Public License (GPL) Version 2, available from the file
# COPYING in the main directory of this source tree, or the BSD-type
# license below:
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#      Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#      Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials provided
#      with the distribution.
#
#      Neither the name of NTESS Corporation, Open Grid Computing nor
#      the names of any contributors may be used to endorse or promote
#      products derived from this software without specific prior
#      written permission.
#
#      Modified source versions must be plainly marked as such, and
#      must not be misrepresented as being the original software.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
from __future__ import print_function
from builtins import str
import sys
import argparse
from sosdb import Sos

def fmt_size(size):
    if size < 1000.0:
        return "{0:8.1f}KB".format(size / 1000.0)
    size /= 1000000.0
    if size < 1000.0:
        return "{0:8.1f}MB".format(size)
    size /= 1000.0
    if size < 1000.0:
        return "{0:8.1f} GB".format(size)
    size /= 1000.0
    if size < 1000.0:
        return "{0:8.1f} TB".format(size)
    size /= 1000.0
    return "{0:8.1f} PB".format(size)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create a SOS DB")
    parser.add_argument("--path", required=True,
                        help="The path to the database.")
    parser.add_argument("--create", action="store_true",
                        help="Create a new SOS database. " \
                        "The --path parameter specifies the path to the new " \
                        "database.")
    parser.add_argument("--mode", metavar="FILE-CREATION-MASK", type=int,
                        help="The permissions to assign to SOS database files.")
    parser.add_argument("--no-root", action="store_true",
                        help="Use this option if you do not want a ROOT partition created.")
    parser.add_argument("--query", action="store_true",
                        help="Query a container's storage information")
    parser.add_argument("--verbose", action="store_true",
                        help="Request verbose query output")
    args = parser.parse_args()

    cont = Sos.Container()

    if not args.create and not args.query:
        print("Either the --create or --query options must be specified.")
        sys.exit(1)

    if args.create:
        try:
            # Create the database
            if args.mode:
                cont.create(args.path, o_mode=args.mode)
            else:
                cont.create(args.path)
            # Create a ROOT partition unless the user asked us not to
            if not args.no_root:
                cont.open(args.path)
                cont.part_create("ROOT")
                part = cont.part_by_name("ROOT")
                part.state_set("primary")
        except Exception as ex:
            print("The database could not be created.")
            print(ex)
            sys.exit(1)

    if args.query:
        import datetime as dt
        cont.open(args.path)
        pi = cont.part_iter()
        print("{0:18} {1:10} {2:18} {3:18} {4:10} {5}". \
              format("Name", "State", "Accessed", "Modified", "Size", "Path"))
        print("{0} {1} {2} {3} {4} {5}". \
              format('-'.ljust(18,'-'), '-'.ljust(10,'-'),
                     '-'.ljust(18,'-'), '-'.ljust(18,'-'), '-'.ljust(11,'-'),
                     '-'.ljust(20,'-')))
        for p in pi:
            stat = p.stat()
            accessed = dt.datetime.fromtimestamp(stat.accessed)
            modified = dt.datetime.fromtimestamp(stat.modified)
            print("{0:18} {1:10} {2:18} {3:18} {4:10} {5}". \
                  format(p.name(), str(p.state()),
                         accessed.strftime("%m/%d/%y %H:%M:%S"),
                         modified.strftime("%m/%d/%y %H:%M:%S"),
                         fmt_size(stat.size), p.path()))
