#!/usr/bin/env python
import argparse
import sys
import os
import math

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Create a component input file for the sos_cmd.")
    parser.add_argument("--pfx",
                        help="Specify the component name prefix; default='nid'")
    parser.add_argument("--cols",
                        default=0,
                        help="Specify the number of rows")
    parser.add_argument("--first",
                        default=1,
                        help="Specify the first component number; default=1")
    parser.add_argument("--last",
                        default=1000,
                        help="Specify the last component number; default=1000")
    args = parser.parse_args()

    first = float(args.first)
    last = float(args.last)
    count = last - first + 1
    cols = math.sqrt(count)
    rows = int(count / cols)
    if count % cols:
        rows = rows + 1
    cur_col = 0
    cur_row = 0
    # print("# Id, State, Name, Description, CabinetId, x_3d, y_3d, z_3d, x_2d, y_2d")
    for comp_id in range(int(first), int(last)+1):
        print("{0},{1},{2},{3},{4},{5},{6},{7},{8},{9}".
              format(comp_id, 0, "{0}{1:05}".format(args.pfx, comp_id), "Compute Node", 0, 0, 0, 0,
                     cur_col, cur_row))
        cur_col = cur_col + 1
        if cur_col >= cols:
            cur_col = 0
            cur_row = cur_row + 1

